castelos_info = {
    'Abrantes': {'district': 'Santarém',
    'council': 'Abrantes',
    'century': 'Século XII',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.4643515, -8.1945228],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/abrantes.html'},
    'Aguiar de Sousa': {'district': 'Porto',
    'council': 'Paredes',
    'century': 'Século X (conjectural)',
    'king': 'Sem informação',
    'coordinates': [41.123935, -8.437502],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/aguiarSousa.html'},
    'Alcácer do Sal': {'district': 'Setúbal',
    'council': 'Alcácer do Sal',
    'century': 'Século XII',
    'king': 'Sem informação',
    'coordinates': [38.3724158, -8.513346499999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/alcacerSal.html'},
    'Alcanede': {'district': 'Santarém',
    'council': 'Alcanede',
    'century': 'Entre os Séculos VIII e X',
    'king': 'Origem árabe (provável)',
    'coordinates': [39.417275, -8.821493],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/alcanede.html'},
    'Alcobaça': {'district': 'Leiria',
    'council': 'Alcobaça',
    'century': '650 (conjectural)',
    'king': 'Origem árabe ou visigótica',
    'coordinates': [39.550576, -8.982282],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/alcobaca.html'},
    'Alcantarilha': {'district': 'Faro',
    'council': 'Silves',
    'century': 'Século XII',
    'king': 'D. Afonso III (conjectural)',
    'coordinates': [37.12836, -8.345636],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/alcantarilha.html'},
    'Alfaiates': {'district': 'Guarda',
    'council': 'Sabugal',
    'century': 'Fim do Século XII / início do Século XIII',
    'king': 'Reinado de Leão, Espanha (conjectural)',
    'coordinates': [40.3903217, -6.911438299999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/alfaiates.html'},
    'Alfeizerão': {'district': 'Leiria',
    'council': 'Alcobaça',
    'century': '1147 (conjectural)',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.500369, -9.109731],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/alfeizerao.html'},
    'Aljezur': {'district': 'Faro',
    'council': 'Aljezur',
    'century': 'Século X',
    'king': 'Origem árabe',
    'coordinates': [37.316438, -8.805129],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/aljezur.html'},
    'Aljustrel': {'district': 'Beja',
    'council': 'Aljustrel',
    'century': 'Século XII',
    'king': 'Origem árabe',
    'coordinates': [37.88119, -8.167258],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/aljustrel.html'},
    'Alenquer': {'district': 'Lisboa',
    'council': 'Alenquer',
    'century': '1148',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.057798, -9.007086],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/alenquer.html'},
    'Almada': {'district': 'Setúbal',
    'council': 'Almada',
    'century': '1170',
    'king': 'Afonso I de Portugal',
    'coordinates': [38.684639, -9.155417],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/almada.html'},
    'Almourol': {'district': 'Santarém',
    'council': 'Vila Nova da Barquinha',
    'century': '1171',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.4619434, -8.383911699999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/almourol.html'},
    'Alter do Chão': {'district': 'Portalegre',
    'council': 'Alter do Chão',
    'century': '1357',
    'king': 'D. Pedro I',
    'coordinates': [39.1989436, -7.658481900000001],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/alterChao.html'},
    'Alva': {'district': 'Bragança',
    'council': 'Freixo de Espada à Cinta',
    'century': 'Século XII',
    'king': 'Desconhecido',
    'coordinates': [41.031700, -6.935173],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/alva.html'},
    'Alvito': {'district': 'Beja',
    'council': 'Alvito',
    'century': '1494',
    'king': 'D. João II / D. Manuel I',
    'coordinates': [38.257885, -7.992048],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/alvito.html'},
    'Alvor': {'district': 'Faro',
    'council': 'Portimão',
    'century': 'Século VII A.C.',
    'king': 'Origem fenícia',
    'coordinates': [37.129314, -8.593406],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/alvor.html'},
    'Amieira': {'district': 'Portalegre',
    'council': 'Amieira',
    'century': '1350',
    'king': 'D. Afonso IV',
    'coordinates': [39.508066, -7.816316],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/amieira.html'},
    'Alpalhão': {'district': 'Portalegre',
    'council': 'Nisa',
    'century': '1300 (aproximado)',
    'king': 'D. Dinis',
    'coordinates': [39.418047, -7.618498],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/alpalhao.html'},
    'Arraiolos': {'district': 'Évora',
    'council': 'Arraiolos',
    'century': '1306',
    'king': 'D. Dinis I',
    'coordinates': [38.725212, -7.987588],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/arraiolos.html'},
    'Ansiães': {'district': 'Bragança',
    'council': 'Carrazeda de Ansiães',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [41.2027472, -7.305501899999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/ansiaes.html'},
    'Atouguia da Baleia': {'district': 'Leiria',
    'council': 'Peniche',
    'century': 'Século XIII ou XIV',
    'king': 'Desconhecido',
    'coordinates': [39.340171, -9.325203],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/atouguiaBaleia.html'},
    'Avô': {'district': 'Coimbra',
    'council': 'Oliveira do Hospital',
    'century': 'Século XII',
    'king': 'D. Afonso Henriques',
    'coordinates': [40.2931918, -7.9043698],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/avo.html'},
    'Barcelos': {'district': 'Braga',
    'council': 'Barcelos',
    'century': 'Século XV',
    'king': 'Pedro, infante de Portugal',
    'coordinates': [41.528398, -8.621817],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/barcelos.html'},
    'Braga': {'district': 'Braga',
    'council': 'São João do Souto',
    'century': 'Século XIII',
    'king': 'D. Dinis',
    'coordinates': [41.551453, -8.423975],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/braga.html'},
    'Bragança': {'district': 'Bragança',
    'council': 'Santa Maria',
    'century': 'Século XIII',
    'king': 'Fernão Mendes ou D. Sancho I ',
    'coordinates': [41.804254, -6.749231],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/braganca.html'},
    'Cabeço de Vide': {'district': 'Portalegre',
    'council': 'Fronteira',
    'century': 'Século XII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [39.1345018, -7.586576099999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/cabecoVide.html'},
    'Cacela': {'district': 'Faro',
    'council': 'Vila Real de Santo António',
    'century': '1770',
    'king': 'D. João VI',
    'coordinates': [37.138962, -7.592350],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/cacela.html'},
    'Caminha': {'district': 'Viana do Castelo',
    'council': 'Caminha',
    'century': 'Século X',
    'king': 'Desconhecido',
    'coordinates': [41.871724, -8.839023],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/caminha.html'},
    'Carrapatoso': {'district': 'Leiria',
    'council': 'Torres Novas',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [39.611665, -8.498044],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/carrapatoso.html'},
    'Castelo Bom': {'district': 'Guarda',
    'council': 'Almeida',
    'century': '1297',
    'king': 'D. Dinis',
    'coordinates': [40.620890, -6.901444],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/casteloBom.html'},
    'Castelo Melhor': {'district': 'Guarda',
    'council': 'Vila Nova de Foz Côa',
    'century': '1209 ou 1210',
    'king': 'Afonso VII de Leão',
    'coordinates': [41.023076, -7.066499],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/casteloMelhor.html'},
    'Castelo Mendo': {'district': 'Guarda',
    'council': 'Almeida',
    'century': '1297',
    'king': 'D. Dinis',
    'coordinates': [40.594151, -6.948964],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/casteloMendo.html'},
    'Castelo Novo': {'district': 'Castelo Branco',
    'council': 'Fundão',
    'century': 'Século XII (conjectural)',
    'king': 'D. Sancho I (conjectural)',
    'coordinates': [40.077841, -7.496163],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/casteloNovo.html'},
    'Castelo Rodrigo': {'district': 'Guarda',
    'council': 'Figueira de Castelo Rodrigo',
    'century': 'Século XII ou Século XIII',
    'king': 'Afonso IX de Leão',
    'coordinates': [40.877297, -6.964119],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/casteloRodrigo.html'},
    'Castro Marim': {'district': 'Faro',
    'council': 'Castro Marim',
    'century': 'Século VIII A.C.',
    'king': 'Desconhecido',
    'coordinates': [37.2185168, -7.4419526],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/castroMarim.html'},
    'Castro Laboreiro': {'district': 'Viana do Castelo',
    'council': 'Melgaço',
    'century': 'Século IX',
    'king': 'Afonso III de Leão',
    'coordinates': [42.022631, -8.158017],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/castroLaboreiro.html'},
    'Celorico da Beira': {'district': 'Guarda',
    'council': 'Celorico da Beira',
    'century': 'Século XII',
    'king': 'Afonso I de Portugal',
    'coordinates': [40.6372227, -7.3918755],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/celoricoBeira.html'},
    'Ceras': {'district': 'Santarém',
    'council': 'Tomar',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [39.698054, -8.358738],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/ceras.html'},
    'Chaves': {'district': 'Vila Real',
    'council': 'Chaves',
    'century': 'Século IX',
    'king': 'Afonso III das Astúrias',
    'coordinates': [41.739750, -7.471755],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/chaves.html'},
    'Coimbra': {'district': 'Coimbra',
    'council': 'Coimbra',
    'century': 'Século XI',
    'king': 'D. Sesnando Davides',
    'coordinates': [40.208928, -8.428889],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/coimbra.html'},
    'Cola': {'district': 'Beja',
    'council': 'Ourique',
    'century': 'Idade do Bronze',
    'king': 'N.a.',
    'coordinates': [37.579120, -8.300533],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/cola.html'},
    'Covilhã': {'district': 'Castelo Branco',
    'council': 'Covilhã',
    'century': '1188 (conjectural)',
    'king': 'D. Sancho I de Portugal',
    'coordinates': [40.281135, -7.507905],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/covilha.html'},
    'Estremoz': {'district': 'Évora',
    'council': 'Estremoz',
    'century': 'Século XII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [38.8418362, -7.5921941],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/estremoz.html'},
    'Évora': {'district': 'Évora',
    'council': 'Évora',
    'century': 'Século XIV',
    'king': 'D. Afonso IV',
    'coordinates': [38.574309, -7.915187],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/evora.html'},
    'Évora Monte': {'district': 'Évora',
    'council': 'Estremoz',
    'century': '1160 (conjectural)',
    'king': 'Afonso I de Portugal',
    'coordinates': [38.7718235, -7.7160286],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/evoraMonte.html'},
    'Faria': {'district': 'Braga',
    'council': 'Barcelos',
    'century': 'Século IX ou X',
    'king': 'Desconhecido',
    'coordinates': [41.496587, -8.647404],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/faria.html'},
    'Faro': {'district': 'Faro',
    'council': 'Faro (Sé e São Pedro)',
    'century': '1249',
    'king': 'D. Afonso III',
    'coordinates': [37.012162, -7.9342495],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/faro.html'},
    'Ferreira de Aves': {'district': 'Viseu',
    'council': 'Sátão',
    'century': 'Século XII ou XIII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [40.798565, -7.689698],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/ferreiraAves.html'},
    'Folgosinho': {'district': 'Guarda',
    'council': 'Gouveia',
    'century': 'Século XII (conjectural)',
    'king': 'D. Sancho I (conjectural)',
    'coordinates': [40.511046, -7.512139],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/folgosinho.html'},
    'Freixo de Espada à Cinta': {'district': 'Bragança',
    'council': 'Freixo de Espada à Cinta',
    'century': 'Século XII ou XIII',
    'king': 'D. Afonso Henriques ou D. Sancho I',
    'coordinates': [41.092655, -6.804545],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/freixoEspada.html'},
    'Gaia': {'district': 'Porto',
    'council': 'Vila Nova de Gaia',
    'century': 'Desconhecido',
    'king': 'Origem árabe',
    'coordinates': [41.139697, -8.624706],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/gaia.html'},
    'Germanelo': {'district': 'Coimbra',
    'council': 'Penela',
    'century': '1142',
    'king': 'Afonso I',
    'coordinates': [40.026291, -8.430486],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/germanelo.html'},
    'Giraldo': {'district': 'Évora',
    'council': 'Nossa Senhora de Guadalupe',
    'century': 'Idade do Bronze',
    'king': 'Desconhecido',
    'coordinates': [38.537479, -8.0331564],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/giraldo.html'},
    'Gouveia': {'district': 'Guarda',
    'council': 'Gouveia',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.494058, -7.594016],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/gouveia.html'},
    'Guarda': {'district': 'Guarda',
    'council': 'Guarda',
    'century': 'Século XII',
    'king': 'D. Sancho I',
    'coordinates': [40.5374579, -7.271479500000001],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/guarda.html'},
    'Guimarães': {'district': 'Guimarães',
    'council': 'Oliveira do Castelo',
    'century': 'Anterior a 958',
    'king': 'Desconhecido',
    'coordinates': [41.4478935, -8.2903191],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/guimaraes.html'},
    'Idanha-a-Nova': {'district': 'Castelo Branco',
    'council': 'Idanha-a-Nova',
    'century': '1187',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.919864, -7.236517],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/idanhaNova.html'},
    'Idanha-a-Velha': {'district': 'Castelo Branco',
    'council': 'Idanha-a-Nova',
    'century': '1197 (conjectural)',
    'king': 'D. Sancho I',
    'coordinates': [39.996443, -7.143644],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/idanhaVelha.html'},
    'Lagos': {'district': 'Faro',
    'council': 'Lagos',
    'century': 'Desconhecido',
    'king': 'Origem árabe',
    'coordinates': [37.099831, -8.669866],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/lagos.html'},
    'Lamego': {'district': 'Viseu',
    'council': 'Lamego',
    'century': 'Desconhecido',
    'king': 'Origem árabe',
    'coordinates': [41.099318, -7.808686],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/lamego.html'},
    'Lanhoso': {'district': 'Braga',
    'council': 'Póvoa de Lanhoso',
    'century': 'Século XII ou XIII',
    'king': 'Desconhecido',
    'coordinates': [41.5868295, -8.281177399999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/lanhoso.html'},
    'Leiria': {'district': 'Leiria',
    'council': 'Leiria',
    'century': 'Século XII',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.747416, -8.809389],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/leiria.html'},
    'Lindoso': {'district': 'Viana do Castelo',
    'council': 'Ponte da Barca',
    'century': 'Desconhecido',
    'king': 'D. Afonso III',
    'coordinates': [41.867116, -8.1991214],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/lindoso.html'},
    'Linhares da Beira': {'district': 'Guarda',
    'council': 'Celorico da Beira',
    'century': 'Século XII (conjectural)',
    'king': 'D. Afonso Henriques ou D. Sancho I',
    'coordinates': [40.5413189, -7.4612253],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/linharesBeira.html'},
    'Longroiva': {'district': 'Guarda',
    'council': 'Mêda',
    'century': 'Século X',
    'king': 'Desconhecido',
    'coordinates': [40.963839, -7.208643],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/longroiva.html'},
    'Loulé': {'district': 'Faro',
    'council': 'Loulé',
    'century': 'Desconhecido',
    'king': 'Origem árabe',
    'coordinates': [37.13965, -8.0238611],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/loule.html'},
    'Lourinhã': {'district': 'Lisboa',
    'council': 'Lourinhã',
    'century': 'Século XII',
    'king': 'Desconhecido',
    'coordinates': [39.2427012, -9.3139033],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/lourinha.html'},
    'Lousã': {'district': 'Coimbra',
    'council': 'Lousã',
    'century': 'Século XI',
    'king': 'D. Sesnando Davides',
    'coordinates': [40.1004146, -8.235504299999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/lousa.html'},
    'Marialva': {'district': 'Guarda',
    'council': 'Mêda',
    'century': '1179 (conjectural)',
    'king': 'D. Afonso Henriques',
    'coordinates': [40.9134756, -7.2321575],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/marialva.html'},
    'Mau Vizinho': {'district': 'Vila Real',
    'council': 'Chaves',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [41.8174926, -7.233657399999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/mauVizinho.html'},
    'Mau Vizinho (Évora)': {'district': 'Évora',
    'council': 'Arraiolos',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [38.7119704, -7.866338],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/mauVizinhoEvora.html'},
    'Melgaço': {'district': 'Viana do Castelo',
    'council': 'Melgaço',
    'century': '1170 (conjectural)',
    'king': 'D. Afonso Henriques',
    'coordinates': [42.1141539, -8.259675],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/melgaco.html'},
    'Mértola': {'district': 'Beja',
    'council': 'Mértola',
    'century': '(930 - 1031)',
    'king': 'Desconhecido',
    'coordinates': [37.638145, -7.6639957],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/mertola.html'},
    'Messejana': {'district': 'Beja',
    'council': 'Aljustrel',
    'century': 'Desconhecido',
    'king': 'Origem árabe',
    'coordinates': [37.8362757, -8.2463813],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/messejana.html'},
    'Miranda do Douro': {'district': 'Bragança',
    'council': 'Miranda do Douro',
    'century': 'Desconhecido',
    'king': 'Origem árabe',
    'coordinates': [41.4964679, -6.2751725],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/mirandaDouro.html'},
    'Mogadouro': {'district': 'Bragança',
    'council': 'Mogadouro',
    'century': '1160',
    'king': 'D. Afonso Henriques',
    'coordinates': [41.338271, -6.719729],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/mogadouro.html'},
    'Monforte': {'district': 'Vila Real',
    'council': 'Chaves',
    'century': 'Século XII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [39.054239, -7.438991],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/monforte.html'},
    'Monforte (Fig.C.Rodrigo)': {'district': 'Guarda',
    'council': 'Figueira de Castelo Rodrigo',
    'century': '1188 (conjectural)',
    'king': 'D. Sancho I',
    'coordinates': [40.830022, -7.005778],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/monforteFigRodrigo.html'},
    'Monsanto': {'district': 'Castelo Branco',
    'council': 'Idanha-a-Nova',
    'century': 'Século XII',
    'king': 'Templários',
    'coordinates': [40.036032, -7.113749],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/monsanto.html'},
    'Monsaraz': {'district': 'Évora',
    'council': 'Reguengos de Monsaraz',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [38.4422413, -7.381747],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/monsaraz.html'},
    'Montel': {'district': 'Beja',
    'council': 'Castro Verde',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [37.751893, -7.939980],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/montel.html'},
    'Montemor-o-Velho': {'district': 'Coimbra',
    'council': 'Montemor-o-Velho',
    'century': '1088',
    'king': 'Afonso VI de Leão e Castela',
    'coordinates': [40.1757498, -8.6828502],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/montemorVelho.html'},
    'Moreira de Rei': {'district': 'Guarda',
    'council': 'Trancoso',
    'century': 'Século XII',
    'king': 'D. Afonso Henriques',
    'coordinates': [40.8281492, -7.3205196],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/moreiraRei.html'},
    'Neiva': {'district': 'Viana do Castelo',
    'council': 'Castelo do Neiva',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [41.628107, -8.800649],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/neiva.html'},
    'Numão': {'district': 'Guarda',
    'council': 'Vila Nova de Foz Côa',
    'century': '1130',
    'king': 'D. Afonso Henriques',
    'coordinates': [41.099432, -7.291236],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/numao.html'},
    'Óbidos': {'district': 'Leiria',
    'council': 'Óbidos',
    'century': 'Século XII-Século XIII',
    'king': 'SEM INFO',
    'coordinates': [39.3635196, -9.1569821],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/obidos.html'},
    'Oleiros': {'district': 'Bragança',
    'council': 'Mogadouro',
    'century': 'SEM INFO',
    'king': 'SEM INFO',
    'coordinates': [39.9185272, -7.9137986],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/oleiros.html'},
    'Ourém': {'district': 'Santarém',
    'council': 'Ourém',
    'century': 'Século XII',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.6415143, -8.5922213],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/ourem.html'},
    'Paderne': {'district': 'Faro',
    'council': 'Albufeira',
    'century': 'Séculos XI ou XII ',
    'king': 'Califado Almóada',
    'coordinates': [37.157156, -8.200139],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/paderne.html'},
    'Palmela': {'district': 'Setúbal',
    'council': 'Palmela',
    'century': 'Século XII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [38.5659136, -8.9008231],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/palmela.html'},
    'Pena de Aguiar': {'district': 'Vila Real',
    'council': 'Vila Pouca de Aguiar',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [41.4694994, -7.6801409],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/penaAguiar.html'},
    'Penacova': {'district': 'Coimbra',
    'council': 'Penacova',
    'century': 'Século X',
    'king': 'Desconhecido',
    'coordinates': [40.270312, -8.277381],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/penacova.html'},
    'Penamacor': {'district': 'Castelo Branco',
    'council': 'Penamacor',
    'century': '1199',
    'king': 'D. Sancho I',
    'coordinates': [40.167029, -7.165745],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/penamacor.html'},
    'Penas Róias': {'district': 'Bragança',
    'council': 'Mogadouro',
    'century': '1166',
    'king': 'D. Afonso Henriques',
    'coordinates': [41.3923755, -6.654058999999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/penasRoias.html'},
    'Penedono': {'district': 'Viseu',
    'council': 'Penedono',
    'century': 'Cerca de 900 (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [40.989973, -7.393869899999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/penedono.html'},
    'Penela': {'district': 'Coimbra',
    'council': 'Penela',
    'century': '1140 (conjectural)',
    'king': 'D. Afonso Henriques',
    'coordinates': [40.030956, -8.389906],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/penela.html'},
    'Piconha': {'district': 'Vila Real',
    'council': 'Montalegre',
    'century': 'Século X',
    'king': 'D. Afonso III de Leão (conjectural)',
    'coordinates': [41.893346, -7.865400],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/piconha.html'},
    'Pinhel': {'district': 'Guarda',
    'council': 'Pinhel',
    'century': '1209',
    'king': 'D. Sancho I',
    'coordinates': [40.777174, -7.062011],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/pinhel.html'},
    'Pombal': {'district': 'Leiria',
    'council': 'Pombal',
    'century': '1161',
    'king': 'Gualdim Pais',
    'coordinates': [39.914043, -8.624832],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/pombal.html'},
    'Portelo': {'district': 'Vila Real',
    'council': 'Montalegre',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [41.897248, -7.764721],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/portelo.html'},
    'Porto de Mós': {'district': 'Leiria',
    'council': 'Porto de Mós',
    'century': '1200',
    'king': 'D. Sancho I',
    'coordinates': [39.6034479, -8.818197],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/portoMos.html'},
    'Proença-a-Velha': {'district': 'Castelo Branco',
    'council': 'Idanha-a-Nova',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.025725, -7.238192],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/proencaVelha.html'},
    'Rodão': {'district': 'Castelo Branco',
    'council': 'Vila Velha de Ródão',
    'century': 'Século XII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [39.647479, -7.690130],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/rodao.html'},
    'Relíquias': {'district': 'Faro',
    'council': 'Alcoutim',
    'century': 'Desconhecido',
    'king': 'Origem árabe',
    'coordinates': [37.496780, -7.706082],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/reliquias.html'},
    'Romano da Lousa': {'district': 'Évora',
    'council': 'Mourão',
    'century': 'Séculos II e I a.C.',
    'king': 'Desconhecido',
    'coordinates': [38.359510, -7.405924],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/romanoLousa.html'},
    'Roqueiro de Coruto': {'district': 'Aveiro',
    'council': 'Arouca',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.943179, -8.405667],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/roqueiroCoruto.html'},
    'Sabugal': {'district': 'Guarda',
    'council': 'Sabugal',
    'century': 'Século XII',
    'king': 'Desconhecido',
    'coordinates': [40.3513139, -7.0939806],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/sabugal.html'},
    'São Martinho de Mouros ': {'district': 'Viseu',
    'council': 'Resende',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [41.112037, -7.893548],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/martinhoMouros.html'},
    'São Jorge': {'district': 'Lisboa',
    'council': 'Santa Maria Maior',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [38.7139092, -9.1334762],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/sJorge.html'},
    'Salir': {'district': 'Faro',
    'council': 'Loulé',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [37.24304516747451, -8.046582654278655],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/salir.html'},
    'Salvaterra do Extremo': {'district': 'Castelo Branco',
    'council': 'Idanha-a-Nova',
    'century': 'Século XII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [39.881903, -6.911423],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/salvaterraExtremo.html'},
    'Santa Maria da Feira': {'district': 'Aveiro',
    'council': 'Santa Maria da Feira',
    'century': 'Anterior ao século XI',
    'king': 'Desconhecido',
    'coordinates': [40.9208408, -8.5426301],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/santaMaria.html'},
    'Santarém': {'district': 'Santarém',
    'council': 'Santarém',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [39.233745, -8.675262],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/santarem.html'},
    'Santiago do Cacém': {'district': 'Setúbal',
    'council': 'Santiago do Cacém',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [38.0141375, -8.6988113],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/santiagoCacem.html'},
    'Santo Estêvão': {'district': 'Vila Real',
    'council': 'Chaves',
    'century': '1160',
    'king': 'D. Afonso Henriques',
    'coordinates': [41.759140, -7.419060],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/santoEstevao.html'},
    'Seia': {'district': 'Guarda',
    'council': 'Seia',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.420432, -7.703892],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/seia.html'},
    'Sernancelhe': {'district': 'Viseu',
    'council': 'Sernancelhe',
    'century': 'SEM INFO',
    'king': 'SEM INFO',
    'coordinates': [40.9004694, -7.4947712],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/sernancelhe.html'},
    'Sertã': {'district': 'Castelo Branco',
    'council': 'Sertã',
    'century': 'Século XI ou XII',
    'king': 'Henrique de Borgonha',
    'coordinates': [39.804955, -8.098712],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/serta.html'},
    'Silves': {'district': 'Faro',
    'council': 'Silves',
    'century': '716',
    'king': 'Origem árabe',
    'coordinates': [37.1904974, -8.4384882],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/silves.html'},
    'Sines': {'district': 'Setúbal',
    'council': 'Sines',
    'century': '1424',
    'king': 'D. João I',
    'coordinates': [37.955143, -8.866539],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/sines.html'},
    'Sintra': {'district': 'Lisboa',
    'council': 'Sintra',
    'century': 'Século VIII e Século IX',
    'king': 'Origem árabe',
    'coordinates': [38.792556, -9.3893376],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/sintra.html'},
    'Soure': {'district': 'Coimbra',
    'council': 'soure',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.0567689, -8.6260065],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/soure.html'},
    'Sortelha': {'district': 'Guarda',
    'council': 'Sabugal',
    'century': '1228',
    'king': 'D. Sancho II',
    'coordinates': [40.3307794, -7.2120327],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/sortelha.html'},
    'Tarouca': {'district': 'Viseu',
    'council': 'Tarouca',
    'century': 'Século XI',
    'king': 'Desconhecido',
    'coordinates': [41.018280, -7.774590],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/tarouca.html'},
    'Tavira': {'district': 'Faro',
    'council': 'Tavira',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [37.125495, -7.651201],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/tavira.html'},
    'Tomar': {'district': 'Santarém',
    'council': 'Tomar',
    'century': '1160',
    'king': 'D. Afonso Henriques',
    'coordinates': [39.60338040000001, -8.417603],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/tomar.html'},
    'Torres Novas': {'district': 'Santarém',
    'council': 'Torres Novas',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [39.4795102, -8.5407046],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/torresNovas.html'},
    'Torres Vedras': {'district': 'Lisboa',
    'council': 'Torres Vedras',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [39.0938226, -9.2612063],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/torresVedras.html'},
    'Trancoso': {'district': 'Guarda',
    'council': 'Trancoso',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.7786777, -7.3483052],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/trancoso.html'},
    'Veiros': {'district': 'Évora',
    'council': 'Estremoz',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [38.953079, -7.508489],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXIII/veiros.html'},
    'Velho de Alcoutim': {'district': 'Faro',
    'council': 'Alcoutim',
    'century': 'Século VIII',
    'king': 'Califado Omíada',
    'coordinates': [37.480799, -7.472090],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/velhoAlcoutim.html'},
    'Velho do Degebe': {'district': 'Évora',
    'council': 'Reguengos de Monsaraz',
    'century': 'Idade do Ferro',
    'king': 'Desconhecido',
    'coordinates': [38.366400, -7.594978],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/velhoDegebe.html'},
    'Vermoim': {'district': 'Vila Nova de Famalicão',
    'council': 'Vermoim',
    'century': 'Anterior a 977',
    'king': 'Desconhecido',
    'coordinates': [41.4302985, -8.449532099999999],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/vermoim.html'},
    'Viana do Alentejo': {'district': 'Évora',
    'council': 'Viana do Alentejo',
    'century': '1313',
    'king': 'D. Dinis I',
    'coordinates': [38.332083, -8.001853],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/vianaAlentejo.html'},
    'Vidigueira': {'district': 'Beja',
    'council': 'Vidigueira',
    'century': 'Século XII (conjectural)',
    'king': 'Desconhecido',
    'coordinates': [38.213009, -7.802361],
    'link': 'https://www.castelosdeportugal.pt/castelos/CastelosSECXII/vidigueira.html'},
    'Vila Verde dos Francos': {'district': 'Lisboa',
    'council': 'Alenquer',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [39.150142, -9.113891],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/verdeFrancos.html'},
    'Vila Viçosa': {'district': 'Évora',
    'council': 'Vila Viçosa',
    'century': 'Século XIV',
    'king': 'D. Dinis',
    'coordinates': [38.7799758, -7.414871600000001],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pos)SECXIII/vilaVicosa.html'},
    'Vilar Maior': {'district': 'Guarda',
    'council': 'Sabugal',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.476673, -6.940697],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/vilarMaior.html'},
    'Vinhais': {'district': 'Bragança',
    'council': 'Vinhais',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [41.835635, -7.000098],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/vinhais.html'},
    'Viseu': {'district': 'Viseu',
    'council': 'Viseu',
    'century': 'Desconhecido',
    'king': 'Desconhecido',
    'coordinates': [40.661728, -7.908750],
    'link': 'https://www.castelosdeportugal.pt/castelos/Castelos(pre)SECXII/viseu.html'}
    }








castelos_scraping_result = {
 'Abrantes': {'district': 'Santarém',
  'council': 'Abrantes',
  'century': 'Século XII',
  'king': 'D. Afonso Henriques',
  'coordinates': [39.4643515, -8.1945228]},
 'Aguiar Sousa': {'district': 'Porto',
  'council': 'Paredes',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.1247849, -8.4385601]},
 'Alcácer do Sal': {'district': 'Setúbal',
  'council': 'Alcácer do Sal',
  'century': 'Século XII',
  'king': 'SEM INFO',
  'coordinates': [38.3724158, -8.513346499999999]},
 'Alcanede': {'district': 'Santarém',
  'council': 'Alcanede',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.4153425, -8.8216051]},
 'Alcobaça': {'district': 'Leiria',
  'council': 'Alcobaça',
  'century': '(c.650)',
  'king': 'SEM INFO',
  'coordinates': [39.5506995, -8.9858727]},
 'Alcantarilha': {'district': 'Faro',
  'council': 'Silves',
  'century': 'Séc. XII',
  'king': 'SEM INFO',
  'coordinates': [37.1309704, -8.3482749]},
 'Alfaiates': {'district': 'Guarda',
  'council': 'Sabugal',
  'century': '(Século XII)?',
  'king': 'SEM INFO',
  'coordinates': [40.3903217, -6.911438299999999]},
 'Alfeizerão': {'district': 'Leiria',
  'council': 'Alcobaça',
  'century': 'c. 1147',
  'king': 'D. Afonso Henriques',
  'coordinates': [39.4998922, -9.1034759]},
 'Aljezur': {'district': 'Faro',
  'council': 'Aljezur',
  'century': 'Século X',
  'king': 'SEM INFO',
  'coordinates': [37.31657, -8.7992645]},
 'Aljustrel': {'district': 'Beja',
  'council': 'Aljustrel',
  'century': 'Sec XII',
  'king': 'SEM INFO',
  'coordinates': [37.8760582, -8.1649833]},
 'Alenquer': {'district': 'Lisboa',
  'council': 'Alenquer',
  'century': '1148',
  'king': 'D. Afonso Henriques',
  'coordinates': [39.0558984, -9.0095998]},
 'Almada': {'district': 'Setúbal',
  'council': 'Almada',
  'century': '1170',
  'king': 'Afonso I de Portugal',
  'coordinates': [38.6765238, -9.165104699999999]},
 'Almourol': {'district': 'Santarém',
  'council': 'Vila Nova da Barquinha',
  'century': '1171',
  'king': 'SEM INFO',
  'coordinates': [39.4619434, -8.383911699999999]},
 'Alter do Chão': {'district': 'Portalegre',
  'council': 'Alter do Chão',
  'century': '1357',
  'king': 'D. Pedro I',
  'coordinates': [39.1989436, -7.658481900000001]},
 'Alva': {'district': 'Bragança',
  'council': 'Freixo de Espada à Cinta',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [36.778261, -119.4179324]},
 'Alvito': {'district': 'Beja',
  'council': 'Alvito',
  'century': '1494',
  'king': 'SEM INFO',
  'coordinates': [38.2316311, -8.024700500000002]},
 'Alvor': {'district': 'Faro',
  'council': 'Portimão',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.130505, -8.5935063]},
 'Amieira': {'district': 'Portalegre',
  'council': 'Amieira',
  'century': '1350',
  'king': 'D. Afonso IV',
  'coordinates': [38.302566, -7.589737200000001]},
 'Alpalhão': {'district': 'Portalegre',
  'council': 'Nisa',
  'century': '(séc XII)?',
  'king': 'SEM INFO',
  'coordinates': [39.4124913, -7.622266499999999]},
 'Arraiolos': {'district': 'Évora',
  'council': 'Arraiolos',
  'century': '1306',
  'king': 'D. Dinis I',
  'coordinates': [38.7247674, -7.9868486]},
 'Ansiães': {'district': 'Bragança',
  'council': 'Carrazeda de Ansiães',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.2027472, -7.305501899999999]},
 'Atouguia da Baleia': {'district': 'Leiria',
  'council': 'Peniche',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.33974329999999, -9.3270108]},
 'Avô': {'district': 'Coimbra',
  'council': 'Oliveira do Hospital',
  'century': 'Século XII',
  'king': 'D. Afonso Henriques',
  'coordinates': [40.2931918, -7.9043698]},
 'Barcelos': {'district': 'Braga',
  'council': 'Barcelos',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.5320504, -8.6190525]},
 'Braga': {'district': 'Braga',
  'council': 'São João do Souto',
  'century': 'SEM INFO',
  'king': 'D. Dinis',
  'coordinates': [41.5454486, -8.426506999999999]},
 'Bragança': {'district': 'Bragança',
  'council': 'Santa Maria',
  'century': 'Século XIII',
  'king': 'Fernão Mendes ou D. Sancho I ',
  'coordinates': [41.8061131, -6.756737999999999]},
 'Cabeço de Vide': {'district': 'Portalegre',
  'council': 'Fronteira',
  'century': '(Séc. XII)?',
  'king': 'SEM INFO',
  'coordinates': [39.1345018, -7.586576099999999]},
 'Cacela': {'district': 'Faro',
  'council': 'Vila Real de Santo António',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Caminha': {'district': 'Viana do Castelo',
  'council': 'Caminha',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.8732082, -8.837845399999999]},
 'Carrapatoso': {'district': 'Leiria',
  'council': 'Torres Novas',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Castelo Bom': {'district': 'Guarda',
  'council': 'Almeida',
  'century': '1297',
  'king': 'D. Dinis',
  'coordinates': [40.6220298, -6.8887202]},
 'Castelo Melhor': {'district': 'Guarda',
  'council': 'Vila Nova de Foz Côa',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.0333116, -7.0821162]},
 'Castelo Mendo': {'district': 'Guarda',
  'council': 'Almeida',
  'century': '1297',
  'king': 'D. Dinis',
  'coordinates': [40.593213, -6.947753199999999]},
 'Castelo Novo': {'district': 'Castelo Branco',
  'council': 'Fundão',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.0778556, -7.496546299999999]},
 'Castelo Rodrigo': {'district': 'Guarda',
  'council': 'Figueira de Castelo Rodrigo',
  'century': '(Século XII)?',
  'king': 'SEM INFO',
  'coordinates': [40.8628504, -6.910180599999999]},
 'Castro Marim': {'district': 'Faro',
  'council': 'Castro Marim',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.2185168, -7.4419526]},
 'Castro Laboreiro': {'district': 'Viana do Castelo',
  'council': 'Melgaço',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [42.0225932, -8.158104699999999]},
 'Celorico da Beira': {'district': 'Guarda',
  'council': 'Celorico da Beira',
  'century': 'Séc. XII',
  'king': 'Afonso I de Portugal',
  'coordinates': [40.6372227, -7.3918755]},
 'Ceras': {'district': 'Santarém',
  'council': 'Tomar',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Chaves': {'district': 'Vila Real',
  'council': 'Chaves',
  'century': 'Século IX',
  'king': 'Afonso III das Astúrias',
  'coordinates': [41.7396156, -7.4718311]},
 'Coimbra': {'district': 'Coimbra',
  'council': 'SEM INFO',
  'century': '(Século XII)?',
  'king': 'SEM INFO',
  'coordinates': [40.2033145, -8.4102573]},
 'Cola': {'district': 'Beja',
  'council': 'Ourique',
  'century': 'Idade do Bronze',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Covilhã': {'district': 'Castelo Branco',
  'council': 'Covilhã',
  'century': '(1188)?',
  'king': 'D. Sancho I de Portugal',
  'coordinates': [40.2805633, -7.504327199999999]},
 'Estremoz': {'district': 'Évora',
  'council': 'Estremoz',
  'century': '(Século XII)?',
  'king': 'SEM INFO',
  'coordinates': [38.8418362, -7.5921941]},
 'Évora': {'district': 'Évora',
  'council': 'SEM INFO',
  'century': 'SEM INFO',
  'king': 'D. Afonso IV',
  'coordinates': [38.571431, -7.913501999999999]},
 'Évora Monte': {'district': 'Évora',
  'council': 'Estremoz',
  'century': '(1160)?',
  'king': 'Afonso I de Portugal',
  'coordinates': [38.7718235, -7.7160286]},
 'Faria': {'district': 'Braga',
  'council': 'Barcelos',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.4965619, -8.6474042]},
 'Faro': {'district': 'Faro',
  'council': 'Faro (Sé e São Pedro)',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.012162, -7.9342495]},
 'Ferreira de Aves': {'district': 'Viseu',
  'council': 'Sátão',
  'century': '(Séc XII)?',
  'king': 'SEM INFO',
  'coordinates': [40.8097982, -7.6653617]},
 'Folgosinho': {'district': 'Guarda',
  'council': 'Gouveia',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [36.778261, -119.4179324]},
 'Freixo de Espada à Cinta': {'district': 'Bragança',
  'council': 'Freixo de Espada à Cinta',
  'century': '(Séc. XII)?',
  'king': 'SEM INFO',
  'coordinates': [41.0900806, -6.8087993]},
 'Gaia': {'district': 'Porto',
  'council': 'Vila Nova de Gaia',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.139884, -8.6260868]},
 'Germanelo': {'district': 'Coimbra',
  'council': 'Penela',
  'century': '1142',
  'king': 'Afonso I',
  'coordinates': [36.778261, -119.4179324]},
 'Giraldo': {'district': 'Évora',
  'council': 'Nossa Senhora de Guadalupe',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [38.537479, -8.0331564]},
 'Gouveia': {'district': 'Guarda',
  'council': 'Gouveia',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.4923318, -7.5936526]},
 'Guarda': {'district': 'Guarda',
  'council': 'SEM INFO',
  'century': 'Século XII',
  'king': 'D. Sancho I',
  'coordinates': [40.5374579, -7.271479500000001]},
 'Guimarães': {'district': 'Guimarães',
  'council': 'Oliveira do Castelo',
  'century': '(ant. a 958)',
  'king': 'SEM INFO',
  'coordinates': [41.4478935, -8.2903191]},
 'Idanha-a-Nova': {'district': 'Castelo Branco',
  'council': 'Idanha-a-Nova',
  'century': '(séc XII)?',
  'king': 'SEM INFO',
  'coordinates': [39.924752, -7.2415895]},
 'Idanha-a-Velha': {'district': 'Castelo Branco',
  'council': 'Idanha-a-Nova',
  'century': '(séc XII)?',
  'king': 'SEM INFO',
  'coordinates': [40.0014856, -7.1520926]},
 'Lagos': {'district': 'Faro',
  'council': 'Lagos',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.1027881, -8.6730275]},
 'Lamego': {'district': 'Viseu',
  'council': 'Lamego',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.0994421, -7.8089599]},
 'Lanhoso': {'district': 'Braga',
  'council': 'Póvoa de Lanhoso',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.5868295, -8.281177399999999]},
 'Leiria': {'district': 'Leiria',
  'council': 'SEM INFO',
  'century': 'Século XII',
  'king': 'D. Afonso Henriques',
  'coordinates': [39.74953310000001, -8.807682999999999]},
 'Lindoso': {'district': 'Viana do Castelo',
  'council': 'Ponte da Barca',
  'century': 'SEM INFO',
  'king': 'D. Afonso III',
  'coordinates': [41.867116, -8.1991214]},
 'Linhares da Beira': {'district': 'Guarda',
  'council': 'Celorico da Beira',
  'century': '(Século XII)?',
  'king': 'SEM INFO',
  'coordinates': [40.5413189, -7.4612253]},
 'Longroiva': {'district': 'Guarda',
  'council': 'Mêda',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.9664008, -7.1898025]},
 'Loulé': {'district': 'Faro',
  'council': 'Loulé',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.13965, -8.0238611]},
 'Lourinhã': {'district': 'Lisboa',
  'council': 'Lourinhã',
  'century': 'Séc. XII',
  'king': 'SEM INFO',
  'coordinates': [39.2427012, -9.3139033]},
 'Lousã': {'district': 'Coimbra',
  'council': 'Lousã',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.1004146, -8.235504299999999]},
 'Marialva': {'district': 'Guarda',
  'council': 'Mêda',
  'century': 'c. 1179',
  'king': 'D. Afonso Henriques',
  'coordinates': [40.9134756, -7.2321575]},
 'Mau Vizinho': {'district': 'Vila Real',
  'council': 'Chaves',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.8174926, -7.233657399999999]},
 'Mau Vizinho(Évora)': {'district': 'Évora',
  'council': 'Arraiolos',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [38.7119704, -7.866338]},
 'Melgaço': {'district': 'Viana do Castelo',
  'council': 'Melgaço',
  'century': 'c. 1170',
  'king': 'D. Afonso Henriques',
  'coordinates': [42.1141539, -8.259675]},
 'Mértola': {'district': 'Beja',
  'council': 'Mértola',
  'century': '(930 - 1031)',
  'king': 'SEM INFO',
  'coordinates': [37.638145, -7.6639957]},
 'Messejana': {'district': 'Beja',
  'council': 'Aljustrel',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.8362757, -8.2463813]},
 'Miranda do Douro': {'district': 'Bragança',
  'council': 'Miranda do Douro',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.4964679, -6.2751725]},
 'Mogadouro': {'district': 'Bragança',
  'council': 'Mogadouro',
  'century': '1160',
  'king': 'D. Afonso Henriques',
  'coordinates': [41.3419345, -6.7094364]},
 'Monforte': {'district': 'Vila Real',
  'council': 'Chaves',
  'century': '(Século XII)?',
  'king': 'SEM INFO',
  'coordinates': [39.053627, -7.439591099999999]},
 'Monforte (Fig.C.Rodrigo)': {'district': 'Guarda',
  'council': 'Figueira de Castelo Rodrigo',
  'century': '(1188)?',
  'king': 'SEM INFO',
  'coordinates': [39.0528283, -7.4377345]},
 'Monsanto': {'district': 'Castelo Branco',
  'council': 'Idanha-a-Nova',
  'century': 'Séc. XII',
  'king': 'Templários',
  'coordinates': [40.0377108, -7.1147639]},
 'Monsaraz': {'district': 'Évora',
  'council': 'Reguengos de Monsaraz',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [38.4422413, -7.381747]},
 'Montel': {'district': 'Beja',
  'council': 'Castro Verde',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Montemor-o-Velho': {'district': 'Coimbra',
  'council': 'Montemor-o-Velho',
  'century': '(1088)',
  'king': 'Afonso VI de Leão e Castela',
  'coordinates': [40.1757498, -8.6828502]},
 'Moreira de Rei': {'district': 'Guarda',
  'council': 'Trancoso',
  'century': 'Século XII',
  'king': 'D. Afonso Henriques',
  'coordinates': [40.8281492, -7.3205196]},
 'Neiva': {'district': 'Viana do Castelo',
  'council': 'Castelo do Neiva',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.6280562, -8.8008408]},
 'Numão': {'district': 'Guarda',
  'council': None,
  'century': '1130',
  'king': 'D. Afonso Henriques',
  'coordinates': [41.1060928, -7.281471799999999]},
 'Óbidos': {'district': 'Leiria',
  'council': 'Óbidos',
  'century': 'Século XII-Século XIII',
  'king': 'SEM INFO',
  'coordinates': [39.3635196, -9.1569821]},
 'Oleiros': {'district': 'Bragança',
  'council': 'Mogadouro',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.9185272, -7.9137986]},
 'Ourém': {'district': 'Santarém',
  'council': 'Ourém',
  'century': 'Século XII',
  'king': 'D. Afonso Henriques',
  'coordinates': [39.6415143, -8.5922213]},
 'Paderne': {'district': 'Faro',
  'council': 'Albufeira',
  'century': 'Séculos XI ou XII ',
  'king': 'Califado Almóada',
  'coordinates': [37.1764814, -8.201073]},
 'Palmela': {'district': 'Setúbal',
  'council': 'Palmela',
  'century': '(Séc. XII)?',
  'king': 'SEM INFO',
  'coordinates': [38.5659136, -8.9008231]},
 'Pena de Aguiar': {'district': 'Vila Real',
  'council': 'Vila Pouca de Aguiar',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.4694994, -7.6801409]},
 'Penacova': {'district': 'Coimbra',
  'council': 'Penacova',
  'century': 'Século X',
  'king': 'SEM INFO',
  'coordinates': [40.2704883, -8.28054]},
 'Penamacor': {'district': 'Castelo Branco',
  'council': 'Penamacor',
  'century': '1199',
  'king': 'D. Sancho I',
  'coordinates': [40.1680132, -7.1716603]},
 'Penas Róias': {'district': 'Bragança',
  'council': 'Mogadouro',
  'century': '1166',
  'king': 'D. Afonso Henriques',
  'coordinates': [41.3923755, -6.654058999999999]},
 'Penedono': {'district': 'Viseu',
  'council': 'Penedono',
  'century': 'c. 900',
  'king': 'SEM INFO',
  'coordinates': [40.989973, -7.393869899999999]},
 'Penela': {'district': 'Coimbra',
  'council': 'Penela',
  'century': 'c. 1140',
  'king': 'D. Afonso Henriques',
  'coordinates': [40.0292279, -8.3908296]},
 'Piconha': {'district': 'Vila Real',
  'council': 'Montalegre',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Pinhel': {'district': 'Guarda',
  'council': 'Pinhel',
  'century': '1209',
  'king': 'D. Sancho I',
  'coordinates': [40.7732736, -7.0685935]},
 'Pombal': {'district': 'Leiria',
  'council': 'Pombal',
  'century': '1161',
  'king': 'Gualdim Pais',
  'coordinates': [39.8902544, -8.551753099999999]},
 'Portelo': {'district': 'Vila Real',
  'council': 'Montalegre',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Porto de Mós': {'district': 'Leiria',
  'council': 'Porto de Mós',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.6034479, -8.818197]},
 'Proença-a-Velha': {'district': 'Castelo Branco',
  'council': 'Idanha-a-Nova',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.0261468, -7.240212399999999]},
 'Rodão': {'district': 'Castelo Branco',
  'council': 'Vila Velha de Ródão',
  'century': '(séc XII)?',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Relíquias': {'district': 'Faro',
  'council': 'Alcoutim',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.7007645, -8.539144]},
 'Romano da Lousa': {'district': 'Évora',
  'council': 'Mourão',
  'century': 'Séculos II e I a.C.',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Roqueiro de Coruto': {'district': 'Aveiro',
  'council': 'Arouca',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Sabugal': {'district': 'Guarda',
  'council': 'Sabugal',
  'century': '? Século XII',
  'king': 'SEM INFO',
  'coordinates': [40.3513139, -7.0939806]},
 'São Martinho de Mouros ': {'district': 'Viseu',
  'council': 'Resende',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.1033672, -7.8971879]},
 'São Jorge': {'district': 'Lisboa',
  'council': 'Santa Maria Maior',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [38.7139092, -9.1334762]},
 'Salir': {'district': 'Faro',
  'council': 'Loulé',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.24101830000001, -8.044013099999999]},
 'Salvaterra do Extremo': {'district': 'Castelo Branco',
  'council': 'Idanha-a-Nova',
  'century': '(séc XII)?',
  'king': 'SEM INFO',
  'coordinates': [39.90628150000001, -6.9531225]},
 'Santa Maria da Feira': {'district': 'Aveiro',
  'council': 'Santa Maria da Feira',
  'century': 'Anterior ao século XI',
  'king': 'SEM INFO',
  'coordinates': [40.9208408, -8.5426301]},
 'Santarém': {'district': 'Santarém',
  'council': 'Marvila (ext.)',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.77323130000001, -8.6320582]},
 'Santiago do Cacém': {'district': 'Setúbal',
  'council': 'Santiago do Cacém',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [38.0141375, -8.6988113]},
 'Santo Estêvão': {'district': 'Vila Real',
  'council': 'Chaves',
  'century': '1160',
  'king': 'D. Afonso Henriques',
  'coordinates': [38.88084509999999, -8.715083100000001]},
 'Seia': {'district': 'Guarda',
  'council': 'Seia',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.4148619, -7.707845000000001]},
 'Sernancelhe': {'district': 'Viseu',
  'council': 'Sernancelhe',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.9004694, -7.4947712]},
 'Sertã': {'district': 'Castelo Branco',
  'council': 'Sertã',
  'century': 'Século XI ou XII',
  'king': 'Henrique de Borgonha',
  'coordinates': [39.8429602, -8.1717637]},
 'Silves': {'district': 'Faro',
  'council': 'Silves',
  'century': '(716)',
  'king': 'SEM INFO',
  'coordinates': [37.1904974, -8.4384882]},
 'Sines': {'district': 'Setúbal',
  'council': 'Sines',
  'century': '1424',
  'king': 'D. João I',
  'coordinates': [37.9556972, -8.866227799999999]},
 'Sintra': {'district': 'Lisboa',
  'council': 'Sintra',
  'century': 'Século VIII e Século IX',
  'king': 'SEM INFO',
  'coordinates': [38.792556, -9.3893376]},
 'Soure': {'district': 'Coimbra',
  'council': 'soure',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.0567689, -8.6260065]},
 'Sortelha': {'district': 'Guarda',
  'council': 'Sabugal',
  'century': '1228',
  'king': 'D. Sancho II',
  'coordinates': [40.3307794, -7.2120327]},
 'Tarouca': {'district': 'Tarouca',
  'council': 'SEM INFO',
  'century': 'Século XI',
  'king': 'SEM INFO',
  'coordinates': [41.0174461, -7.775003600000001]},
 'Tavira': {'district': 'Faro',
  'council': 'Tavira',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [37.1244406, -7.651199699999999]},
 'Tomar': {'district': 'Santarém',
  'council': 'Tomar',
  'century': '1160',
  'king': 'D. Afonso Henriques',
  'coordinates': [39.60338040000001, -8.417603]},
 'Torres Novas': {'district': 'Santarém',
  'council': 'Torres Novas',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.4795102, -8.5407046]},
 'Torres Vedras': {'district': 'Lisboa',
  'council': 'Torres Vedras',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.0938226, -9.2612063]},
 'Trancoso': {'district': 'Guarda',
  'council': 'Trancoso',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.7786777, -7.3483052]},
 'Veiros': {'district': 'Évora',
  'council': 'Estremoz',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [38.9645607, -7.5138947]},
 'Velho de Alcoutim': {'district': 'Faro',
  'council': 'Alcoutim',
  'century': 'Século VIII',
  'king': 'Califado Omíada',
  'coordinates': [37.4808543, -7.472303699999999]},
 'Velho do Degebe': {'district': 'Évora',
  'council': 'Reguengos de Monsaraz',
  'century': 'Idade do Ferro',
  'king': 'SEM INFO',
  'coordinates': [39.39987199999999, -8.224454]},
 'Vermoim': {'district': 'Vila Nova de Famalicão',
  'council': 'Vermoim',
  'century': '(ant. a 977)',
  'king': 'SEM INFO',
  'coordinates': [41.4302985, -8.449532099999999]},
 'Viana do Alentejo': {'district': 'Évora',
  'council': 'Viana do Alentejo',
  'century': '1313',
  'king': 'D. Dinis I',
  'coordinates': [38.3320312, -8.0018482]},
 'Vidigueira': {'district': 'Beja',
  'council': 'Vidigueira',
  'century': '(Séc. XII)?',
  'king': 'SEM INFO',
  'coordinates': [38.2129922, -7.8023076]},
 'Vila Verde dos Francos': {'district': 'Lisboa',
  'council': 'Alenquer',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [39.1545356, -9.113387999999999]},
 'Vila Viçosa': {'district': 'Évora',
  'council': 'Vila Viçosa',
  'century': 'Século XIV',
  'king': 'D. Dinis I',
  'coordinates': [38.7799758, -7.414871600000001]},
 'Vilar Maior': {'district': 'Guarda',
  'council': 'Sabugal',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [40.80091729999999, -8.0447255]},
 'Vinhais': {'district': 'Bragança',
  'council': 'Vinhais',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.8224297, -7.0498442]},
 'Viseu': {'district': 'Viseu',
  'council': 'Santa Maria de Viseu',
  'century': 'SEM INFO',
  'king': 'SEM INFO',
  'coordinates': [41.0357637, -7.6222146]}}





castelos_html = {
 'Abrantes': 'CastelosSECXII/abrantes.html',
 'Aguiar Sousa': 'Castelos(pre)SECXII/aguiarSousa.html',
 'Alcácer do Sal': 'CastelosSECXII/alcacerSal.html',
 'Alcanede': 'Castelos(pre)SECXII/alcanede.html',
 'Alcobaça': 'Castelos(pre)SECXII/alcobaca.html',
 'Alcantarilha': 'CastelosSECXII/alcantarilha.html',
 'Alfaiates': 'CastelosSECXII/alfaiates.html',
 'Alfeizerão': 'CastelosSECXII/alfeizerao.html',
 'Aljezur': 'Castelos(pre)SECXII/aljezur.html',
 'Aljustrel': 'CastelosSECXII/aljustrel.html',
 'Alenquer': 'CastelosSECXII/alenquer.html',
 'Almada': 'CastelosSECXII/almada.html',
 'Almourol': 'CastelosSECXII/almourol.html',
 'Alter do Chão': 'Castelos(pos)SECXIII/alterChao.html',
 'Alva': 'Castelos(pre)SECXII/alva.html',
 'Alvito': 'Castelos(pos)SECXIII/alvito.html',
 'Alvor': 'Castelos(pre)SECXII/alvor.html',
 'Amieira': 'Castelos(pos)SECXIII/amieira.html',
 'Alpalhão': 'CastelosSECXII/alpalhao.html',
 'Arraiolos': 'Castelos(pos)SECXIII/arraiolos.html',
 'Ansiães': 'Castelos(pre)SECXII/ansiaes.html',
 'Atouguia da Baleia': 'Castelos(pre)SECXII/atouguiaBaleia.html',
 'Avô': 'CastelosSECXII/avo.html',
 'Barcelos': 'Castelos(pre)SECXII/barcelos.html',
 'Braga': 'CastelosSECXIII/braga.html',
 'Bragança': 'CastelosSECXIII/braganca.html',
 'Cabeço de Vide': 'CastelosSECXII/cabecoVide.html',
 'Cacela': 'Castelos(pre)SECXII/cacela.html',
 'Caminha': 'Castelos(pre)SECXII/caminha.html',
 'Carrapatoso': 'Castelos(pre)SECXII/carrapatoso.html',
 'Castelo Bom': 'CastelosSECXIII/casteloBom.html',
 'Castelo Melhor': 'Castelos(pre)SECXII/casteloMelhor.html',
 'Castelo Mendo': 'CastelosSECXIII/casteloMendo.html',
 'Castelo Novo': 'CastelosSECXII/casteloNovo.html',
 'Castelo Rodrigo': 'CastelosSECXII/casteloRodrigo.html',
 'Castro Marim': 'Castelos(pre)SECXII/castroMarim.html',
 'Castro Laboreiro': 'Castelos(pre)SECXII/castroLaboreiro.html',
 'Celorico da Beira': 'CastelosSECXII/celoricoBeira.html',
 'Ceras': 'Castelos(pre)SECXII/ceras.html',
 'Chaves': 'Castelos(pre)SECXII/chaves.html',
 'Coimbra': 'CastelosSECXII/coimbra.html',
 'Cola': 'Castelos(pre)SECXII/cola.html',
 'Covilhã': 'CastelosSECXII/covilha.html',
 'Estremoz': 'CastelosSECXII/estremoz.html',
 'Évora': 'Castelos(pos)SECXIII/evora.html',
 'Évora Monte': 'CastelosSECXII/evoraMonte.html',
 'Faria': 'Castelos(pre)SECXII/faria.html',
 'Faro': 'Castelos(pre)SECXII/faro.html',
 'Ferreira de Aves': 'CastelosSECXII/ferreiraAves.html',
 'Folgosinho': 'Castelos(pre)SECXII/folgosinho.html',
 'Freixo de Espada à Cinta': 'CastelosSECXII/freixoEspada.html',
 'Gaia': 'Castelos(pre)SECXII/gaia.html',
 'Germanelo': 'CastelosSECXII/germanelo.html',
 'Giraldo': 'Castelos(pre)SECXII/giraldo.html',
 'Gouveia': 'Castelos(pre)SECXII/gouveia.html',
 'Guarda': 'CastelosSECXII/guarda.html',
 'Guimarães': 'Castelos(pre)SECXII/guimaraes.html',
 'Idanha-a-Nova': 'CastelosSECXII/idanhaNova.html',
 'Idanha-a-Velha': 'CastelosSECXII/idanhaVelha.html',
 'Lagos': 'Castelos(pre)SECXII/lagos.html',
 'Lamego': 'Castelos(pre)SECXII/lamego.html',
 'Lanhoso': 'Castelos(pre)SECXII/lanhoso.html',
 'Leiria': 'CastelosSECXII/leiria.html',
 'Lindoso': 'CastelosSECXIII/lindoso.html',
 'Linhares da Beira': 'CastelosSECXII/linharesBeira.html',
 'Longroiva': 'Castelos(pre)SECXII/longroiva.html',
 'Loulé': 'Castelos(pre)SECXII/loule.html',
 'Lourinhã': 'CastelosSECXII/lourinha.html',
 'Lousã': 'Castelos(pre)SECXII/lousa.html',
 'Marialva': 'CastelosSECXII/marialva.html',
 'Mau Vizinho': 'Castelos(pre)SECXII/mauVizinho.html',
 'Mau Vizinho(Évora)': 'Castelos(pre)SECXII/mauVizinhoEvora.html',
 'Melgaço': 'CastelosSECXII/melgaco.html',
 'Mértola': 'Castelos(pre)SECXII/mertola.html',
 'Messejana': 'Castelos(pre)SECXII/messejana.html',
 'Miranda do Douro': 'Castelos(pre)SECXII/mirandaDouro.html',
 'Mogadouro': 'CastelosSECXII/mogadouro.html',
 'Monforte': 'CastelosSECXII/monforte.html',
 'Monforte (Fig.C.Rodrigo)': 'CastelosSECXII/monforteFigRodrigo.html',
 'Monsanto': 'CastelosSECXII/monsanto.html',
 'Monsaraz': 'CastelosSECXII/monsaraz.html',
 'Montel': 'Castelos(pre)SECXII/montel.html',
 'Montemor-o-Velho': 'Castelos(pre)SECXII/montemorVelho.html',
 'Moreira de Rei': 'CastelosSECXII/moreiraRei.html',
 'Neiva': 'Castelos(pre)SECXII/neiva.html',
 'Numão': 'CastelosSECXII/numao.html',
 'Óbidos': 'CastelosSECXII/obidos.html',
 'Oleiros': 'Castelos(pre)SECXII/oleiros.html',
 'Ourém': 'CastelosSECXII/ourem.html',
 'Paderne': 'Castelos(pre)SECXII/paderne.html',
 'Palmela': 'CastelosSECXII/palmela.html',
 'Pena de Aguiar': 'Castelos(pre)SECXII/penaAguiar.html',
 'Penacova': 'Castelos(pre)SECXII/penacova.html',
 'Penamacor': 'CastelosSECXII/penamacor.html',
 'Penas Róias': 'CastelosSECXII/penasRoias.html',
 'Penedono': 'Castelos(pre)SECXII/penedono.html',
 'Penela': 'CastelosSECXII/penela.html',
 'Piconha': 'Castelos(pre)SECXII/piconha.html',
 'Pinhel': 'CastelosSECXIII/pinhel.html',
 'Pombal': 'CastelosSECXII/pombal.html',
 'Portelo': 'Castelos(pre)SECXII/portelo.html',
 'Porto de Mós': 'Castelos(pre)SECXII/portoMos.html',
 'Proença-a-Velha': 'Castelos(pre)SECXII/proencaVelha.html',
 'Rodão': 'CastelosSECXII/rodao.html',
 'Relíquias': 'Castelos(pre)SECXII/reliquias.html',
 'Romano da Lousa': 'Castelos(pre)SECXII/romanoLousa.html',
 'Roqueiro de Coruto': 'Castelos(pre)SECXII/roqueiroCoruto.html',
 'Sabugal': 'CastelosSECXII/sabugal.html',
 'São Martinho de Mouros ': 'Castelos(pre)SECXII/martinhoMouros.html',
 'São Jorge': 'Castelos(pre)SECXII/sJorge.html',
 'Salir': 'Castelos(pre)SECXII/salir.html',
 'Salvaterra do Extremo': 'CastelosSECXII/salvaterraExtremo.html',
 'Santa Maria da Feira': 'Castelos(pre)SECXII/santaMaria.html',
 'Santarém': 'Castelos(pre)SECXII/santarem.html',
 'Santiago do Cacém': 'Castelos(pre)SECXII/santiagoCacem.html',
 'Santo Estêvão': 'CastelosSECXII/santoEstevao.html',
 'Seia': 'Castelos(pre)SECXII/seia.html',
 'Sernancelhe': 'Castelos(pre)SECXII/sernancelhe.html',
 'Sertã': 'CastelosSECXII/serta.html',
 'Silves': 'Castelos(pre)SECXII/silves.html',
 'Sines': 'Castelos(pos)SECXIII/sines.html',
 'Sintra': 'Castelos(pre)SECXII/sintra.html',
 'Soure': 'Castelos(pre)SECXII/soure.html',
 'Sortelha': 'CastelosSECXIII/sortelha.html',
 'Tarouca': 'Castelos(pre)SECXII/tarouca.html',
 'Tavira': 'Castelos(pre)SECXII/tavira.html',
 'Tomar': 'CastelosSECXII/tomar.html',
 'Torres Novas': 'Castelos(pre)SECXII/torresNovas.html',
 'Torres Vedras': 'Castelos(pre)SECXII/torresVedras.html',
 'Trancoso': 'Castelos(pre)SECXII/trancoso.html',
 'Veiros': 'CastelosSECXIII/veiros.html',
 'Velho de Alcoutim': 'Castelos(pre)SECXII/velhoAlcoutim.html',
 'Velho do Degebe': 'Castelos(pre)SECXII/velhoDegebe.html',
 'Vermoim': 'Castelos(pre)SECXII/vermoim.html',
 'Viana do Alentejo': 'Castelos(pos)SECXIII/vianaAlentejo.html',
 'Vidigueira': 'CastelosSECXII/vidigueira.html',
 'Vila Verde dos Francos': 'Castelos(pre)SECXII/verdeFrancos.html',
 'Vila Viçosa': 'Castelos(pos)SECXIII/vilaVicosa.html',
 'Vilar Maior': 'Castelos(pre)SECXII/vilarMaior.html',
 'Vinhais': 'Castelos(pre)SECXII/vinhais.html',
 'Viseu': 'Castelos(pre)SECXII/viseu.html'}
